test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Oracle Object Storage (S3-compatível) — produção
oci:
  service: S3
  endpoint: https://<%= Rails.application.credentials.dig(:oci, :namespace) %>.compat.objectstorage.sa-saopaulo-1.oraclecloud.com
  access_key_id: <%= Rails.application.credentials.dig(:oci, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:oci, :secret_access_key) %>
  region: sa-saopaulo-1
  bucket: tsuru-attachments
  force_path_style: true
